version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo Building the project...
      - chmod +x ./gradlew
      - ./gradlew build -x test
      - cp build/libs/Donghae_zip-0.0.1-SNAPSHOT.jar .
      - cp -r scripts .
      - cp appspec.yml .
      - zip -r deployment-package.zip .
artifacts:
  files:
    - deployment-package.zip  # 최종 배포 파일 S3에 업로드
  discard-paths: no
  name: DonghaeArtifact  # CodeDeploy에서 사용할 S3 아티팩트 이름
