version: 0.2

phases:
  install:
    commands:
      - echo "===== Installing dependencies ====="
      - npm install
  pre_build:
    commands:
      - echo "===== Creating .env file ====="
      - echo "REACT_APP_API_URL=$REACT_APP_API_URL" > .env
      - echo "REACT_APP_KAKAO_API_KEY=$REACT_APP_KAKAO_API_KEY" >> .env
  build:
    commands:
      - echo "===== Building Frontend ====="
      - npm run build
  post_build:
    commands:
      - echo "===== Deploying to S3 ====="
      - aws s3 sync build/ s3://donghae-front --delete
      - echo "===== Invalidating CloudFront Cache ====="
      - aws cloudfront create-invalidation --distribution-id E2ZQWLLPHFUX25 --paths "/*"

artifacts:
  files:
    - "**/*"
